### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by rcemper** [ELynx/i2b2-on-iris#18]
#1)
failed to solve: containers.intersystems.com/intersystems/irishealth-community:2022.1.0.131.0: containers.intersys
tems.com/intersystems/irishealth-community:2022.1.0.131.0: not found
#2)
ERROR #5002: ObjectScript error: <CLASS DOES NOT EXIST>Instance+1^%ZHSLIB.Context.Manager.1 
*%SYSTEM.Context.HealthShare.Manager

**Comment by FLSOpenRepo** [comment]
We have updated the contents of the project to the current version. This error does not appear.
