### ISSUE TITLE
Add the documentation in README not only in PDF

### ISSUE THREAD

**Issue by evshvarov** [ELynx/i2b2-on-iris#4]

**Comment by evshvarov** [comment]
Or in a form of an article on [Developer Community](https://community.intersystems.com/)

**Comment by ELynx** [comment]
I added most important parts of readme from PDF into .md file as well.

More detailed info is still in PDF, since this was summary documentation from my colleagues.

**Comment by ELynx** [comment]
Added docker commands and added how to test successful deploy
